/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/about': RouteRecordInfo<
      '/about',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/archives': RouteRecordInfo<
      '/archives',
      '/archives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/categories': RouteRecordInfo<
      '/categories',
      '/categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/page/[page]': RouteRecordInfo<
      '/page/[page]',
      '/page/:page',
      { page: ParamValue<true> },
      { page: ParamValue<false> },
      | never
    >,
    '/posts/使用Opencode构建Valaxy博客全记录': RouteRecordInfo<
      '/posts/使用Opencode构建Valaxy博客全记录',
      '/posts/%E4%BD%BF%E7%94%A8Opencode%E6%9E%84%E5%BB%BAValaxy%E5%8D%9A%E5%AE%A2%E5%85%A8%E8%AE%B0%E5%BD%95',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/在调用智谱AI的过程中遇到的问题': RouteRecordInfo<
      '/posts/在调用智谱AI的过程中遇到的问题',
      '/posts/%E5%9C%A8%E8%B0%83%E7%94%A8%E6%99%BA%E8%B0%B1AI%E7%9A%84%E8%BF%87%E7%A8%8B%E4%B8%AD%E9%81%87%E5%88%B0%E7%9A%84%E9%97%AE%E9%A2%98',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/提交邮箱和 GitHub 账号邮箱不一致': RouteRecordInfo<
      '/posts/提交邮箱和 GitHub 账号邮箱不一致',
      '/posts/%E6%8F%90%E4%BA%A4%E9%82%AE%E7%AE%B1%E5%92%8C%20GitHub%20%E8%B4%A6%E5%8F%B7%E9%82%AE%E7%AE%B1%E4%B8%8D%E4%B8%80%E8%87%B4',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/阿里云百炼-实现语音克隆': RouteRecordInfo<
      '/posts/阿里云百炼-实现语音克隆',
      '/posts/%E9%98%BF%E9%87%8C%E4%BA%91%E7%99%BE%E7%82%BC-%E5%AE%9E%E7%8E%B0%E8%AF%AD%E9%9F%B3%E5%85%8B%E9%9A%86',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/hello-world': RouteRecordInfo<
      '/posts/hello-world',
      '/posts/hello-world',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tags': RouteRecordInfo<
      '/tags',
      '/tags',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/template': RouteRecordInfo<
      '/template',
      '/template',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'node_modules/valaxy-theme-sakura/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'node_modules/valaxy/client/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'pages/about.md': {
      routes:
        | '/about'
      views:
        | never
    }
    'pages/archives.md': {
      routes:
        | '/archives'
      views:
        | never
    }
    'pages/categories.md': {
      routes:
        | '/categories'
      views:
        | never
    }
    'node_modules/valaxy-theme-sakura/pages/page/[page].vue': {
      routes:
        | '/page/[page]'
      views:
        | never
    }
    'pages/posts/使用Opencode构建Valaxy博客全记录.md': {
      routes:
        | '/posts/使用Opencode构建Valaxy博客全记录'
      views:
        | never
    }
    'pages/posts/在调用智谱AI的过程中遇到的问题.md': {
      routes:
        | '/posts/在调用智谱AI的过程中遇到的问题'
      views:
        | never
    }
    'pages/posts/提交邮箱和 GitHub 账号邮箱不一致.md': {
      routes:
        | '/posts/提交邮箱和 GitHub 账号邮箱不一致'
      views:
        | never
    }
    'pages/posts/阿里云百炼-实现语音克隆.md': {
      routes:
        | '/posts/阿里云百炼-实现语音克隆'
      views:
        | never
    }
    'pages/posts/hello-world.md': {
      routes:
        | '/posts/hello-world'
      views:
        | never
    }
    'pages/tags.md': {
      routes:
        | '/tags'
      views:
        | never
    }
    'pages/template.md': {
      routes:
        | '/template'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
